#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
mount -t tmpfs tmp /tmp
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

export PATH=/bin:/sbin:/usr/bin

hostname kernel

if [ -f /bin/bash ]; then
  exec setsid -c /bin/bash
else
  exec setsid -c /bin/sh
fi
